[package]
name = "norma"
version = "0.1.0"
authors = ["Jordi Pujol Ricarte <jpricarte@inf.ufrgs.br>"]
edition = "2018"
workspace = "../"

[dependencies]
indexmap = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
num-bigint = "0.4"
num-traits = "0.2"
